### ISSUE TITLE
Unable to submit pending changelist with p4-submit

### ISSUE THREAD

**Issue by vschum** [gareth-rees/p4.el#181]
Maybe I'm doing it wrong, but after using p4-change to create a pending changelist based on open files I was unable to find a way to submit said changelist.

**Comment by gareth-rees** [comment]
How did you get on with this?

**Comment by vschum** [comment]
Not bad; however, I haven't done a large amount of testing as my workplace
is going through some changes as far as source control is concerned so I'm
not using p4 on a day-to-day basis anymore.

On Sun, Feb 8, 2015 at 1:24 PM, Gareth Rees <notifications@github.com>
wrote:

> How did you get on with this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gareth-rees/p4.el/issues/181#issuecomment-73423831>.
>



-- 
- Vincent Schumaker
