### ISSUE TITLE
setting P4CONFIG and P4PORT

### ISSUE THREAD

**Issue by mnsanghvi** [gareth-rees/p4.el#189]
Is there a way to set P4CONFIG and P4PORT via variables rather than using p4-set-p4-config and p4-set-p4-port each time I start up emacs ?

**Comment by sfreeland** [comment]
My preferred solution for this is to create a file named "p4env" in the workspace root; all the P4* configuration variables can be set there on a per-workspace basis.

**Comment by gareth-rees** [comment]
See the [Configuring P4](http://www.perforce.com/perforce/doc.current/manuals/p4guide/chapter.configuration.html) section of the Perforce User Guide. The best approach is to do the following:

1. Set `P4CONFIG=.p4config` (or whatever) in your `.profile` on Unix, or via the control panel on Windows.
1. Create a `.p4config` in the root directory of each of your repositories, which contains the appropriate settings for `P4PORT`, `P4USER`, `P4CLIENT` and so on.

**Comment by mnsanghvi** [comment]
I already have it setup in my ~/.bashrc, which gets loaded by my ~/.profile, ~/.bash_profile, and ~/.bash_login, so that I am always pulling in the same environment regardless of which way the shell wants to load everything.

The desktop environment, XFCE, does not however load any one of those files when it starts.  Hence it is not available to the emacs environment when I start it.  If I open up a xterm, I can see that P4CONFIG, P4PORT, P4USER, etc. are all set in the environment via my shell start-up settings.

I am using lightdm as the login manager.

**Comment by gareth-rees** [comment]
I guess you use whatever facility is provided by lightdm, then, to set environment variables that you need in all programs started by lightdm. The [manual is not very helpful](http://manpages.ubuntu.com/manpages/trusty/en/man1/lightdm.1.html), but perhaps [this Stack Exchange answer](http://askubuntu.com/a/150488) is more useful. If all else fails you can always set the environment variables in your `.emacs`.

**Comment by gareth-rees** [comment]
I'm closing this issue as I think this is a problem with lightdm or its documentation (that is, it's not clear how to set environment variables in all programs started by lightdm), not with p4.el.

**Comment by mnsanghvi** [comment]
Sounds good.  I've basically set the environment in ~/.emacs before I do a require on p4.el
