### ISSUE TITLE
p4-update-status should not require P4PORT to be set

### ISSUE THREAD

**Issue by phst** [gareth-rees/p4.el#201]
Currently https://github.com/gareth-rees/p4.el/blob/master/p4.el#L1467 searches for P4PORT in the p4 set output. However, P4PORT is not required to be set; its default is perforce:1666, and if that is the address of a Perforce server, it should just work without P4PORT being set. I'd suggest to add a customization option `p4-require-p4-port` that controls whether P4PORT is required; if that is nil (default should be t to match the current behavior), the search for P4PORT in the p4 set output should be skipped. Happy to provide a patch.

**Comment by gareth-rees** [comment]
I think that it would probably be best to emulate Perforce's behaviour here and not add a customization option.
