### ISSUE TITLE
C-x C-q should not revert

### ISSUE THREAD

**Issue by phst** [gareth-rees/p4.el#205]
The behavior to revert when toggling to read-only mode has been present from day one (https://github.com/gareth-rees/p4.el/blob/7a7b707166f4097e3d58c779b4a8ef66a5545395/p4/p4.el#L2691), but I think it could be considered confusing that an otherwise harmless command like switching to read-only mode can cause a destructive operation like a revert. Maybe the revert should not happen when switching to read-only?

**Comment by gareth-rees** [comment]
I'm inclined to agree. In any case, it's only if the client options include `noallwrite` that reverting makes the buffer read-only.
